### ISSUE TITLE
分区表不允许建立全局索引

### ISSUE THREAD

**Issue by hegja** [dcfs-pmo/dcfs-sonar-plsql-custom#2]
规则简介：
分区表不允许建立全局索引应建立为分区索引，以此降低维护索引的成本，同时便于后续进行数据清理

规则描述：
如建表脚本中含有partition by range则表示该表为分区表，创建索引时必须增加local关键字
错误的索引示例如下：
CREATE INDEX RTH_I4 ON RB_TRAN_HIST (REFERENCE)
TABLESPACE RB_INDX;

正确的索引示例如下：
CREATE INDEX RTH_I4 ON RB_TRAN_HIST(REFERENCE)
LOCAL
TABLESPACE RB_INDX;

规则是否自己实现：否

规则提交人：hegja

**Comment by dcfspmo** [comment]
评估是否能实现中.

**Comment by dcfspmo** [comment]
因为PL/SQL扫描仅针对单个文件生成AST，当建表脚本与索引脚本分离时，无法进行判断
