### ISSUE TITLE
文件句柄必须在异常分支中进行关闭

### ISSUE THREAD

**Issue by hegja** [dcfs-pmo/dcfs-sonar-plsql-custom#3]
规则描述：
使用UTL_FILE.fopen打开文件时，必须在正常分支和异常分支中分别进行UTL_FILE.fclose(v_file_handle)
使用框架cbsd_batch_file_writer.init打开文件时，必须在正常分支和异常分支中分别进行cbsd_batch_file_writer.destroy()
即关闭语句需出现两次

默认的扫描规则中自带文件必须关闭的扫描规则故此处举例均视为文件已有关闭语句体现
存在句柄泄露风险的代码示例如下：
--示例一
BEGIN
	v_file_handle := UTL_FILE.fopen (v_file_path, v_file_name, 'W'); --打开文件
	/*业务处理代码*/
	UTL_FILE.put_line (v_file_handle, v_curline, TRUE); --写文件
	UTL_FILE.fclose (v_file_handle); --关闭文件
END;

--示例二
BEGIN
	cbsd_batch_file_writer.init (p_sys_head_i => v_sys_head_i); --打开文件
	/*业务处理代码*/
	cbsd_batch_file_writer.writebodyfile (p_struct=> SYS.ANYDATA.convertobject
                                               p_struct_name      => v_struct_name ); --写文件
	cbsd_batch_file_writer.destroy(); --关闭文件
END;

正确的代码示例：
--示例一
BEGIN
	v_file_handle := UTL_FILE.fopen (v_file_path, v_file_name, 'W'); --打开文件
	/*业务处理代码*/
	UTL_FILE.put_line (v_file_handle, v_curline, TRUE); --写文件
	UTL_FILE.fclose (v_file_handle); --关闭文件
EXCEPTION
WHEN OTHERS
THEN
	UTL_FILE.fclose (v_file_handle); --关闭文件
	RAISE; --抛出异常信息
END;

--示例二
BEGIN
	cbsd_batch_file_writer.init (p_sys_head_i => v_sys_head_i); --打开文件
	/*业务处理代码*/
	cbsd_batch_file_writer.writebodyfile (p_struct=> SYS.ANYDATA.convertobject
                                               p_struct_name      => v_struct_name ); --写文件
	cbsd_batch_file_writer.destroy(); --关闭文件
EXCEPTION
WHEN OTHERS
THEN
	cbsd_batch_file_writer.destroy(); --关闭文件
	RAISE; --抛出异常信息
END;

规则是否自己实现：否

规则提交人：hegja

**Comment by dcfspmo** [comment]
吃鸡级，待实现
